// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package processor

// instructionUint8 represents an instruction
type instructionUint8 uint8

// InstructionRunnerUint8 runs an instruction
type InstructionRunnerUint8 interface {
	// RunUint8 runs a single instrution (without incrementing the PC for its own read)
	RunUint8(instruction uint8) error
}

// instructionUint16 represents an instruction
type instructionUint16 uint16

// InstructionRunnerUint16 runs an instruction
type InstructionRunnerUint16 interface {
	// RunUint16 runs a single instrution (without incrementing the PC for its own read)
	RunUint16(instruction uint16) error
}

// instructionUint32 represents an instruction
type instructionUint32 uint32

// InstructionRunnerUint32 runs an instruction
type InstructionRunnerUint32 interface {
	// RunUint32 runs a single instrution (without incrementing the PC for its own read)
	RunUint32(instruction uint32) error
}

// instructionUint64 represents an instruction
type instructionUint64 uint64

// InstructionRunnerUint64 runs an instruction
type InstructionRunnerUint64 interface {
	// RunUint64 runs a single instrution (without incrementing the PC for its own read)
	RunUint64(instruction uint64) error
}
