// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package processor

// instructionuint8 represents an instruction
type instructionuint8 uint8

// InstructionRunnerUint8 runs an InstructioninstructionpcType
type InstructionRunnerUint8 interface {
	// RunUint8 runs a single instrution (without incrementing the PC for its own read)
	RunUint8(instruction uint8) error
}

// instructionuint16 represents an instruction
type instructionuint16 uint16

// InstructionRunnerUint16 runs an InstructioninstructionpcType
type InstructionRunnerUint16 interface {
	// RunUint16 runs a single instrution (without incrementing the PC for its own read)
	RunUint16(instruction uint16) error
}

// instructionuint32 represents an instruction
type instructionuint32 uint32

// InstructionRunnerUint32 runs an InstructioninstructionpcType
type InstructionRunnerUint32 interface {
	// RunUint32 runs a single instrution (without incrementing the PC for its own read)
	RunUint32(instruction uint32) error
}

// instructionuint64 represents an instruction
type instructionuint64 uint64

// InstructionRunnerUint64 runs an InstructioninstructionpcType
type InstructionRunnerUint64 interface {
	// RunUint64 runs a single instrution (without incrementing the PC for its own read)
	RunUint64(instruction uint64) error
}
