// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// thirtyTwoiBitRegister represents a register holding the described number of bits.
type thirtyTwoiBitRegister interface {
	// SetFromUint32 sets the value held by this register.
	SetFromUint32(value uint32)

	// ValueAsUint32 gets the value held by this register
	ValueAsUint32() uint32
}
