// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// SixteenBitRegister represents a register holding the described number of bits.
type SixteenBitRegister interface {
	// SetFromUint16 sets the value held by this register.
	SetFromUint16(value uint16)

	// ValueAsUint16 gets the value held by this register
	ValueAsUint16() uint16
}
