// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// sixtyFourfBitRegister represents a register holding the described number of bits.
type sixtyFourfBitRegister interface {
	// SetFromIntName sets the value held by this register.
	SetFromFloat64(value float64)

	// Float64Value gets the value held by this register
	Float64Value() float64
}
