// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// EightBitRegister represents a register holding the described number of bits.
type EightBitRegister interface {
	// SetFromIntName sets the value held by this register.
	SetFromUint8(value uint8)

	// Uint8Value gets the value held by this register
	Uint8Value() uint8
}
