// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// IRegister16 represents a register holding the described number of bits.
type IRegister16 interface {
	// DecrementnBits decrements the register by value
	DecrementUint16(value uint16)

	// InrementnBits increments the register by value
	InrementUint16(value uint16)

	// SetFromUint16 sets the value held by this register.
	SetFromUint16(value uint16)

	// ValueAsUint16 gets the value held by this register
	ValueAsUint16() uint16
}

// SetFromUint16 does nothing for the zero register.
func (register ZeroRegister) SetFromUint16(value uint16) {
}

// ValueAsUint16 gets the value held by this register
func (register ZeroRegister) ValueAsUint16() uint16 {
	return 0
}

// DecrementUint16 decrements the register by value
func (register ZeroRegister) DecrementUint16(value uint16) {}

// InrementUint16 increments the register by value
func (register ZeroRegister) InrementUint16(value uint16) {}
