// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// RegisterUint8 is the register for the backing int
type RegisterUint8 uint8

// SetFromUint8 does nothing for the zero register.
func (register *RegisterUint8) SetFromUint8(value uint8) {
	*register = RegisterUint8(value)
}

// ValueAsUint8 gets the value held by this register
func (register *RegisterUint8) ValueAsUint8() uint8 {
	return uint8(*register)
}

// SetFromUint8 does nothing for the zero register.
func (register ZeroRegister) SetFromUint8(value uint8) {
}

// ValueAsUint8 gets the value held by this register
func (register ZeroRegister) ValueAsUint8() uint8 {
	return 0
}

// RegisterUint16 is the register for the backing int
type RegisterUint16 uint16

// SetFromUint16 does nothing for the zero register.
func (register *RegisterUint16) SetFromUint16(value uint16) {
	*register = RegisterUint16(value)
}

// ValueAsUint16 gets the value held by this register
func (register *RegisterUint16) ValueAsUint16() uint16 {
	return uint16(*register)
}

// SetFromUint16 does nothing for the zero register.
func (register ZeroRegister) SetFromUint16(value uint16) {
}

// ValueAsUint16 gets the value held by this register
func (register ZeroRegister) ValueAsUint16() uint16 {
	return 0
}

// RegisterUint32 is the register for the backing int
type RegisterUint32 uint32

// SetFromUint32 does nothing for the zero register.
func (register *RegisterUint32) SetFromUint32(value uint32) {
	*register = RegisterUint32(value)
}

// ValueAsUint32 gets the value held by this register
func (register *RegisterUint32) ValueAsUint32() uint32 {
	return uint32(*register)
}

// SetFromUint32 does nothing for the zero register.
func (register ZeroRegister) SetFromUint32(value uint32) {
}

// ValueAsUint32 gets the value held by this register
func (register ZeroRegister) ValueAsUint32() uint32 {
	return 0
}

// RegisterUint64 is the register for the backing int
type RegisterUint64 uint64

// SetFromUint64 does nothing for the zero register.
func (register *RegisterUint64) SetFromUint64(value uint64) {
	*register = RegisterUint64(value)
}

// ValueAsUint64 gets the value held by this register
func (register *RegisterUint64) ValueAsUint64() uint64 {
	return uint64(*register)
}

// SetFromUint64 does nothing for the zero register.
func (register ZeroRegister) SetFromUint64(value uint64) {
}

// ValueAsUint64 gets the value held by this register
func (register ZeroRegister) ValueAsUint64() uint64 {
	return 0
}

// RegisterFloat32 is the register for the backing int
type RegisterFloat32 float32

// SetFromFloat32 does nothing for the zero register.
func (register *RegisterFloat32) SetFromFloat32(value float32) {
	*register = RegisterFloat32(value)
}

// ValueAsFloat32 gets the value held by this register
func (register *RegisterFloat32) ValueAsFloat32() float32 {
	return float32(*register)
}

// SetFromFloat32 does nothing for the zero register.
func (register ZeroRegister) SetFromFloat32(value float32) {
}

// ValueAsFloat32 gets the value held by this register
func (register ZeroRegister) ValueAsFloat32() float32 {
	return 0
}

// RegisterFloat64 is the register for the backing int
type RegisterFloat64 float64

// SetFromFloat64 does nothing for the zero register.
func (register *RegisterFloat64) SetFromFloat64(value float64) {
	*register = RegisterFloat64(value)
}

// ValueAsFloat64 gets the value held by this register
func (register *RegisterFloat64) ValueAsFloat64() float64 {
	return float64(*register)
}

// SetFromFloat64 does nothing for the zero register.
func (register ZeroRegister) SetFromFloat64(value float64) {
}

// ValueAsFloat64 gets the value held by this register
func (register ZeroRegister) ValueAsFloat64() float64 {
	return 0
}
