// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// thirtyTwofBitRegister represents a register holding the described number of bits.
type thirtyTwofBitRegister interface {
	// SetFromFloat32 sets the value held by this register.
	SetFromFloat32(value float32)

	// ValueAsFloat32 gets the value held by this register
	ValueAsFloat32() float32
}
