// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// SixteenBitRegister represents a register holding the described number of bits.
type SixteenBitRegister interface {
	// SetFromIntName sets the value held by this register.
	SetFromUint16(value uint16)

	// Uint16Value gets the value held by this register
	Uint16Value() uint16
}
