// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// IFloatRegister32 represents a register holding the described number of bits.
type IFloatRegister32 interface {
	// DecrementnBits decrements the register by value
	DecrementFloat32(value float32)

	// InrementnBits increments the register by value
	InrementFloat32(value float32)

	// SetFromFloat32 sets the value held by this register.
	SetFromFloat32(value float32)

	// ValueAsFloat32 gets the value held by this register
	ValueAsFloat32() float32
}

// SetFromFloat32 does nothing for the zero register.
func (register ZeroRegister) SetFromFloat32(value float32) {
}

// ValueAsFloat32 gets the value held by this register
func (register ZeroRegister) ValueAsFloat32() float32 {
	return 0
}

// DecrementFloat32 decrements the register by value
func (register ZeroRegister) DecrementFloat32(value float32) {}

// InrementFloat32 increments the register by value
func (register ZeroRegister) InrementFloat32(value float32) {}
