// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// IIntRegister32 represents a register holding the described number of bits.
type IIntRegister32 interface {
	// DecrementnBits decrements the register by value
	DecrementUint32(value uint32)

	// InrementnBits increments the register by value
	InrementUint32(value uint32)

	// SetFromUint32 sets the value held by this register.
	SetFromUint32(value uint32)

	// ValueAsUint32 gets the value held by this register
	ValueAsUint32() uint32
}

// SetFromUint32 does nothing for the zero register.
func (register ZeroRegister) SetFromUint32(value uint32) {
}

// ValueAsUint32 gets the value held by this register
func (register ZeroRegister) ValueAsUint32() uint32 {
	return 0
}

// DecrementUint32 decrements the register by value
func (register ZeroRegister) DecrementUint32(value uint32) {}

// InrementUint32 increments the register by value
func (register ZeroRegister) InrementUint32(value uint32) {}
