// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// thirtyTwofBitRegister represents a register holding the described number of bits.
type thirtyTwofBitRegister interface {
	// SetFromIntName sets the value held by this register.
	SetFromFloat32(value float32)

	// Float32Value gets the value held by this register
	Float32Value() float32
}
