// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// sixtyFouriBitRegister represents a register holding the described number of bits.
type sixtyFouriBitRegister interface {
	// SetFromUint64 sets the value held by this register.
	SetFromUint64(value uint64)

	// ValueAsUint64 gets the value held by this register
	ValueAsUint64() uint64
}
