// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// IIntRegister64 represents a register holding the described number of bits.
type IIntRegister64 interface {
	// DecrementnBits decrements the register by value
	DecrementUint64(value uint64)

	// InrementnBits increments the register by value
	InrementUint64(value uint64)

	// SetFromUint64 sets the value held by this register.
	SetFromUint64(value uint64)

	// ValueAsUint64 gets the value held by this register
	ValueAsUint64() uint64
}

// SetFromUint64 does nothing for the zero register.
func (register ZeroRegister) SetFromUint64(value uint64) {
}

// ValueAsUint64 gets the value held by this register
func (register ZeroRegister) ValueAsUint64() uint64 {
	return 0
}

// DecrementUint64 decrements the register by value
func (register ZeroRegister) DecrementUint64(value uint64) {}

// InrementUint64 increments the register by value
func (register ZeroRegister) InrementUint64(value uint64) {}
