// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package registers

// IRegister8 represents a register holding the described number of bits.
type IRegister8 interface {
	// DecrementnBits decrements the register by value
	DecrementUint8(value uint8)

	// InrementnBits increments the register by value
	InrementUint8(value uint8)

	// SetFromUint8 sets the value held by this register.
	SetFromUint8(value uint8)

	// ValueAsUint8 gets the value held by this register
	ValueAsUint8() uint8
}

// SetFromUint8 does nothing for the zero register.
func (register ZeroRegister) SetFromUint8(value uint8) {
}

// ValueAsUint8 gets the value held by this register
func (register ZeroRegister) ValueAsUint8() uint8 {
	return 0
}

// DecrementUint8 decrements the register by value
func (register ZeroRegister) DecrementUint8(value uint8) {}

// InrementUint8 increments the register by value
func (register ZeroRegister) InrementUint8(value uint8) {}
