//  This file was generated by instructionpartgen
//  Changes will be overwritten when regenerated
//  Generator is found at https://github.com/nolag/gocpu/tree/master/instructions/instructionpartgen

package instructions
// Int2 represents an signed 2 bit integer.
type Int2 int8

// Verify checks that value is in range of a 2 bit signed integer
func (value Int2) Verify() bool {
	return value < 2 && value >= -2
}

// Uint2 represents an unsigned 2 bit integer.
type Uint2 uint8

// Verify checks that value is in range of a 2 bit unsigned integer
func (value Uint2) Verify() bool {
	return value < 4
}
// Int3 represents an signed 3 bit integer.
type Int3 int8

// Verify checks that value is in range of a 3 bit signed integer
func (value Int3) Verify() bool {
	return value < 4 && value >= -4
}

// Uint3 represents an unsigned 3 bit integer.
type Uint3 uint8

// Verify checks that value is in range of a 3 bit unsigned integer
func (value Uint3) Verify() bool {
	return value < 8
}
// Int4 represents an signed 4 bit integer.
type Int4 int8

// Verify checks that value is in range of a 4 bit signed integer
func (value Int4) Verify() bool {
	return value < 8 && value >= -8
}

// Uint4 represents an unsigned 4 bit integer.
type Uint4 uint8

// Verify checks that value is in range of a 4 bit unsigned integer
func (value Uint4) Verify() bool {
	return value < 16
}
// Int5 represents an signed 5 bit integer.
type Int5 int8

// Verify checks that value is in range of a 5 bit signed integer
func (value Int5) Verify() bool {
	return value < 16 && value >= -16
}

// Uint5 represents an unsigned 5 bit integer.
type Uint5 uint8

// Verify checks that value is in range of a 5 bit unsigned integer
func (value Uint5) Verify() bool {
	return value < 32
}
// Int6 represents an signed 6 bit integer.
type Int6 int8

// Verify checks that value is in range of a 6 bit signed integer
func (value Int6) Verify() bool {
	return value < 32 && value >= -32
}

// Uint6 represents an unsigned 6 bit integer.
type Uint6 uint8

// Verify checks that value is in range of a 6 bit unsigned integer
func (value Uint6) Verify() bool {
	return value < 64
}
// Int7 represents an signed 7 bit integer.
type Int7 int8

// Verify checks that value is in range of a 7 bit signed integer
func (value Int7) Verify() bool {
	return value < 64 && value >= -64
}

// Uint7 represents an unsigned 7 bit integer.
type Uint7 uint8

// Verify checks that value is in range of a 7 bit unsigned integer
func (value Uint7) Verify() bool {
	return value < 128
}
// Int8 represents an signed 8 bit integer.
type Int8 int16

// Verify checks that value is in range of a 8 bit signed integer
func (value Int8) Verify() bool {
	return value < 128 && value >= -128
}

// Uint8 represents an unsigned 8 bit integer.
type Uint8 uint16

// Verify checks that value is in range of a 8 bit unsigned integer
func (value Uint8) Verify() bool {
	return value < 256
}
// Int9 represents an signed 9 bit integer.
type Int9 int16

// Verify checks that value is in range of a 9 bit signed integer
func (value Int9) Verify() bool {
	return value < 256 && value >= -256
}

// Uint9 represents an unsigned 9 bit integer.
type Uint9 uint16

// Verify checks that value is in range of a 9 bit unsigned integer
func (value Uint9) Verify() bool {
	return value < 512
}
// Int10 represents an signed 10 bit integer.
type Int10 int16

// Verify checks that value is in range of a 10 bit signed integer
func (value Int10) Verify() bool {
	return value < 512 && value >= -512
}

// Uint10 represents an unsigned 10 bit integer.
type Uint10 uint16

// Verify checks that value is in range of a 10 bit unsigned integer
func (value Uint10) Verify() bool {
	return value < 1024
}
// Int11 represents an signed 11 bit integer.
type Int11 int16

// Verify checks that value is in range of a 11 bit signed integer
func (value Int11) Verify() bool {
	return value < 1024 && value >= -1024
}

// Uint11 represents an unsigned 11 bit integer.
type Uint11 uint16

// Verify checks that value is in range of a 11 bit unsigned integer
func (value Uint11) Verify() bool {
	return value < 2048
}
// Int12 represents an signed 12 bit integer.
type Int12 int16

// Verify checks that value is in range of a 12 bit signed integer
func (value Int12) Verify() bool {
	return value < 2048 && value >= -2048
}

// Uint12 represents an unsigned 12 bit integer.
type Uint12 uint16

// Verify checks that value is in range of a 12 bit unsigned integer
func (value Uint12) Verify() bool {
	return value < 4096
}
// Int13 represents an signed 13 bit integer.
type Int13 int16

// Verify checks that value is in range of a 13 bit signed integer
func (value Int13) Verify() bool {
	return value < 4096 && value >= -4096
}

// Uint13 represents an unsigned 13 bit integer.
type Uint13 uint16

// Verify checks that value is in range of a 13 bit unsigned integer
func (value Uint13) Verify() bool {
	return value < 8192
}
// Int14 represents an signed 14 bit integer.
type Int14 int16

// Verify checks that value is in range of a 14 bit signed integer
func (value Int14) Verify() bool {
	return value < 8192 && value >= -8192
}

// Uint14 represents an unsigned 14 bit integer.
type Uint14 uint16

// Verify checks that value is in range of a 14 bit unsigned integer
func (value Uint14) Verify() bool {
	return value < 16384
}
// Int15 represents an signed 15 bit integer.
type Int15 int16

// Verify checks that value is in range of a 15 bit signed integer
func (value Int15) Verify() bool {
	return value < 16384 && value >= -16384
}

// Uint15 represents an unsigned 15 bit integer.
type Uint15 uint16

// Verify checks that value is in range of a 15 bit unsigned integer
func (value Uint15) Verify() bool {
	return value < 32768
}
// Int16 represents an signed 16 bit integer.
type Int16 int32

// Verify checks that value is in range of a 16 bit signed integer
func (value Int16) Verify() bool {
	return value < 32768 && value >= -32768
}

// Uint16 represents an unsigned 16 bit integer.
type Uint16 uint32

// Verify checks that value is in range of a 16 bit unsigned integer
func (value Uint16) Verify() bool {
	return value < 65536
}
// Int17 represents an signed 17 bit integer.
type Int17 int32

// Verify checks that value is in range of a 17 bit signed integer
func (value Int17) Verify() bool {
	return value < 65536 && value >= -65536
}

// Uint17 represents an unsigned 17 bit integer.
type Uint17 uint32

// Verify checks that value is in range of a 17 bit unsigned integer
func (value Uint17) Verify() bool {
	return value < 131072
}
// Int18 represents an signed 18 bit integer.
type Int18 int32

// Verify checks that value is in range of a 18 bit signed integer
func (value Int18) Verify() bool {
	return value < 131072 && value >= -131072
}

// Uint18 represents an unsigned 18 bit integer.
type Uint18 uint32

// Verify checks that value is in range of a 18 bit unsigned integer
func (value Uint18) Verify() bool {
	return value < 262144
}
// Int19 represents an signed 19 bit integer.
type Int19 int32

// Verify checks that value is in range of a 19 bit signed integer
func (value Int19) Verify() bool {
	return value < 262144 && value >= -262144
}

// Uint19 represents an unsigned 19 bit integer.
type Uint19 uint32

// Verify checks that value is in range of a 19 bit unsigned integer
func (value Uint19) Verify() bool {
	return value < 524288
}
// Int20 represents an signed 20 bit integer.
type Int20 int32

// Verify checks that value is in range of a 20 bit signed integer
func (value Int20) Verify() bool {
	return value < 524288 && value >= -524288
}

// Uint20 represents an unsigned 20 bit integer.
type Uint20 uint32

// Verify checks that value is in range of a 20 bit unsigned integer
func (value Uint20) Verify() bool {
	return value < 1048576
}
// Int21 represents an signed 21 bit integer.
type Int21 int32

// Verify checks that value is in range of a 21 bit signed integer
func (value Int21) Verify() bool {
	return value < 1048576 && value >= -1048576
}

// Uint21 represents an unsigned 21 bit integer.
type Uint21 uint32

// Verify checks that value is in range of a 21 bit unsigned integer
func (value Uint21) Verify() bool {
	return value < 2097152
}
// Int22 represents an signed 22 bit integer.
type Int22 int32

// Verify checks that value is in range of a 22 bit signed integer
func (value Int22) Verify() bool {
	return value < 2097152 && value >= -2097152
}

// Uint22 represents an unsigned 22 bit integer.
type Uint22 uint32

// Verify checks that value is in range of a 22 bit unsigned integer
func (value Uint22) Verify() bool {
	return value < 4194304
}
// Int23 represents an signed 23 bit integer.
type Int23 int32

// Verify checks that value is in range of a 23 bit signed integer
func (value Int23) Verify() bool {
	return value < 4194304 && value >= -4194304
}

// Uint23 represents an unsigned 23 bit integer.
type Uint23 uint32

// Verify checks that value is in range of a 23 bit unsigned integer
func (value Uint23) Verify() bool {
	return value < 8388608
}
// Int24 represents an signed 24 bit integer.
type Int24 int32

// Verify checks that value is in range of a 24 bit signed integer
func (value Int24) Verify() bool {
	return value < 8388608 && value >= -8388608
}

// Uint24 represents an unsigned 24 bit integer.
type Uint24 uint32

// Verify checks that value is in range of a 24 bit unsigned integer
func (value Uint24) Verify() bool {
	return value < 16777216
}
// Int25 represents an signed 25 bit integer.
type Int25 int32

// Verify checks that value is in range of a 25 bit signed integer
func (value Int25) Verify() bool {
	return value < 16777216 && value >= -16777216
}

// Uint25 represents an unsigned 25 bit integer.
type Uint25 uint32

// Verify checks that value is in range of a 25 bit unsigned integer
func (value Uint25) Verify() bool {
	return value < 33554432
}
// Int26 represents an signed 26 bit integer.
type Int26 int32

// Verify checks that value is in range of a 26 bit signed integer
func (value Int26) Verify() bool {
	return value < 33554432 && value >= -33554432
}

// Uint26 represents an unsigned 26 bit integer.
type Uint26 uint32

// Verify checks that value is in range of a 26 bit unsigned integer
func (value Uint26) Verify() bool {
	return value < 67108864
}
// Int27 represents an signed 27 bit integer.
type Int27 int32

// Verify checks that value is in range of a 27 bit signed integer
func (value Int27) Verify() bool {
	return value < 67108864 && value >= -67108864
}

// Uint27 represents an unsigned 27 bit integer.
type Uint27 uint32

// Verify checks that value is in range of a 27 bit unsigned integer
func (value Uint27) Verify() bool {
	return value < 134217728
}
// Int28 represents an signed 28 bit integer.
type Int28 int32

// Verify checks that value is in range of a 28 bit signed integer
func (value Int28) Verify() bool {
	return value < 134217728 && value >= -134217728
}

// Uint28 represents an unsigned 28 bit integer.
type Uint28 uint32

// Verify checks that value is in range of a 28 bit unsigned integer
func (value Uint28) Verify() bool {
	return value < 268435456
}
// Int29 represents an signed 29 bit integer.
type Int29 int32

// Verify checks that value is in range of a 29 bit signed integer
func (value Int29) Verify() bool {
	return value < 268435456 && value >= -268435456
}

// Uint29 represents an unsigned 29 bit integer.
type Uint29 uint32

// Verify checks that value is in range of a 29 bit unsigned integer
func (value Uint29) Verify() bool {
	return value < 536870912
}
// Int30 represents an signed 30 bit integer.
type Int30 int32

// Verify checks that value is in range of a 30 bit signed integer
func (value Int30) Verify() bool {
	return value < 536870912 && value >= -536870912
}

// Uint30 represents an unsigned 30 bit integer.
type Uint30 uint32

// Verify checks that value is in range of a 30 bit unsigned integer
func (value Uint30) Verify() bool {
	return value < 1073741824
}
// Int31 represents an signed 31 bit integer.
type Int31 int32

// Verify checks that value is in range of a 31 bit signed integer
func (value Int31) Verify() bool {
	return value < 1073741824 && value >= -1073741824
}

// Uint31 represents an unsigned 31 bit integer.
type Uint31 uint32

// Verify checks that value is in range of a 31 bit unsigned integer
func (value Uint31) Verify() bool {
	return value < 2147483648
}
// Int32 represents an signed 32 bit integer.
type Int32 int64

// Verify checks that value is in range of a 32 bit signed integer
func (value Int32) Verify() bool {
	return value < 2147483648 && value >= -2147483648
}

// Uint32 represents an unsigned 32 bit integer.
type Uint32 uint64

// Verify checks that value is in range of a 32 bit unsigned integer
func (value Uint32) Verify() bool {
	return value < 4294967296
}
// Int33 represents an signed 33 bit integer.
type Int33 int64

// Verify checks that value is in range of a 33 bit signed integer
func (value Int33) Verify() bool {
	return value < 4294967296 && value >= -4294967296
}

// Uint33 represents an unsigned 33 bit integer.
type Uint33 uint64

// Verify checks that value is in range of a 33 bit unsigned integer
func (value Uint33) Verify() bool {
	return value < 8589934592
}
// Int34 represents an signed 34 bit integer.
type Int34 int64

// Verify checks that value is in range of a 34 bit signed integer
func (value Int34) Verify() bool {
	return value < 8589934592 && value >= -8589934592
}

// Uint34 represents an unsigned 34 bit integer.
type Uint34 uint64

// Verify checks that value is in range of a 34 bit unsigned integer
func (value Uint34) Verify() bool {
	return value < 17179869184
}
// Int35 represents an signed 35 bit integer.
type Int35 int64

// Verify checks that value is in range of a 35 bit signed integer
func (value Int35) Verify() bool {
	return value < 17179869184 && value >= -17179869184
}

// Uint35 represents an unsigned 35 bit integer.
type Uint35 uint64

// Verify checks that value is in range of a 35 bit unsigned integer
func (value Uint35) Verify() bool {
	return value < 34359738368
}
// Int36 represents an signed 36 bit integer.
type Int36 int64

// Verify checks that value is in range of a 36 bit signed integer
func (value Int36) Verify() bool {
	return value < 34359738368 && value >= -34359738368
}

// Uint36 represents an unsigned 36 bit integer.
type Uint36 uint64

// Verify checks that value is in range of a 36 bit unsigned integer
func (value Uint36) Verify() bool {
	return value < 68719476736
}
// Int37 represents an signed 37 bit integer.
type Int37 int64

// Verify checks that value is in range of a 37 bit signed integer
func (value Int37) Verify() bool {
	return value < 68719476736 && value >= -68719476736
}

// Uint37 represents an unsigned 37 bit integer.
type Uint37 uint64

// Verify checks that value is in range of a 37 bit unsigned integer
func (value Uint37) Verify() bool {
	return value < 137438953472
}
// Int38 represents an signed 38 bit integer.
type Int38 int64

// Verify checks that value is in range of a 38 bit signed integer
func (value Int38) Verify() bool {
	return value < 137438953472 && value >= -137438953472
}

// Uint38 represents an unsigned 38 bit integer.
type Uint38 uint64

// Verify checks that value is in range of a 38 bit unsigned integer
func (value Uint38) Verify() bool {
	return value < 274877906944
}
// Int39 represents an signed 39 bit integer.
type Int39 int64

// Verify checks that value is in range of a 39 bit signed integer
func (value Int39) Verify() bool {
	return value < 274877906944 && value >= -274877906944
}

// Uint39 represents an unsigned 39 bit integer.
type Uint39 uint64

// Verify checks that value is in range of a 39 bit unsigned integer
func (value Uint39) Verify() bool {
	return value < 549755813888
}
// Int40 represents an signed 40 bit integer.
type Int40 int64

// Verify checks that value is in range of a 40 bit signed integer
func (value Int40) Verify() bool {
	return value < 549755813888 && value >= -549755813888
}

// Uint40 represents an unsigned 40 bit integer.
type Uint40 uint64

// Verify checks that value is in range of a 40 bit unsigned integer
func (value Uint40) Verify() bool {
	return value < 1099511627776
}
// Int41 represents an signed 41 bit integer.
type Int41 int64

// Verify checks that value is in range of a 41 bit signed integer
func (value Int41) Verify() bool {
	return value < 1099511627776 && value >= -1099511627776
}

// Uint41 represents an unsigned 41 bit integer.
type Uint41 uint64

// Verify checks that value is in range of a 41 bit unsigned integer
func (value Uint41) Verify() bool {
	return value < 2199023255552
}
// Int42 represents an signed 42 bit integer.
type Int42 int64

// Verify checks that value is in range of a 42 bit signed integer
func (value Int42) Verify() bool {
	return value < 2199023255552 && value >= -2199023255552
}

// Uint42 represents an unsigned 42 bit integer.
type Uint42 uint64

// Verify checks that value is in range of a 42 bit unsigned integer
func (value Uint42) Verify() bool {
	return value < 4398046511104
}
// Int43 represents an signed 43 bit integer.
type Int43 int64

// Verify checks that value is in range of a 43 bit signed integer
func (value Int43) Verify() bool {
	return value < 4398046511104 && value >= -4398046511104
}

// Uint43 represents an unsigned 43 bit integer.
type Uint43 uint64

// Verify checks that value is in range of a 43 bit unsigned integer
func (value Uint43) Verify() bool {
	return value < 8796093022208
}
// Int44 represents an signed 44 bit integer.
type Int44 int64

// Verify checks that value is in range of a 44 bit signed integer
func (value Int44) Verify() bool {
	return value < 8796093022208 && value >= -8796093022208
}

// Uint44 represents an unsigned 44 bit integer.
type Uint44 uint64

// Verify checks that value is in range of a 44 bit unsigned integer
func (value Uint44) Verify() bool {
	return value < 17592186044416
}
// Int45 represents an signed 45 bit integer.
type Int45 int64

// Verify checks that value is in range of a 45 bit signed integer
func (value Int45) Verify() bool {
	return value < 17592186044416 && value >= -17592186044416
}

// Uint45 represents an unsigned 45 bit integer.
type Uint45 uint64

// Verify checks that value is in range of a 45 bit unsigned integer
func (value Uint45) Verify() bool {
	return value < 35184372088832
}
// Int46 represents an signed 46 bit integer.
type Int46 int64

// Verify checks that value is in range of a 46 bit signed integer
func (value Int46) Verify() bool {
	return value < 35184372088832 && value >= -35184372088832
}

// Uint46 represents an unsigned 46 bit integer.
type Uint46 uint64

// Verify checks that value is in range of a 46 bit unsigned integer
func (value Uint46) Verify() bool {
	return value < 70368744177664
}
// Int47 represents an signed 47 bit integer.
type Int47 int64

// Verify checks that value is in range of a 47 bit signed integer
func (value Int47) Verify() bool {
	return value < 70368744177664 && value >= -70368744177664
}

// Uint47 represents an unsigned 47 bit integer.
type Uint47 uint64

// Verify checks that value is in range of a 47 bit unsigned integer
func (value Uint47) Verify() bool {
	return value < 140737488355328
}
// Int48 represents an signed 48 bit integer.
type Int48 int64

// Verify checks that value is in range of a 48 bit signed integer
func (value Int48) Verify() bool {
	return value < 140737488355328 && value >= -140737488355328
}

// Uint48 represents an unsigned 48 bit integer.
type Uint48 uint64

// Verify checks that value is in range of a 48 bit unsigned integer
func (value Uint48) Verify() bool {
	return value < 281474976710656
}
// Int49 represents an signed 49 bit integer.
type Int49 int64

// Verify checks that value is in range of a 49 bit signed integer
func (value Int49) Verify() bool {
	return value < 281474976710656 && value >= -281474976710656
}

// Uint49 represents an unsigned 49 bit integer.
type Uint49 uint64

// Verify checks that value is in range of a 49 bit unsigned integer
func (value Uint49) Verify() bool {
	return value < 562949953421312
}
// Int50 represents an signed 50 bit integer.
type Int50 int64

// Verify checks that value is in range of a 50 bit signed integer
func (value Int50) Verify() bool {
	return value < 562949953421312 && value >= -562949953421312
}

// Uint50 represents an unsigned 50 bit integer.
type Uint50 uint64

// Verify checks that value is in range of a 50 bit unsigned integer
func (value Uint50) Verify() bool {
	return value < 1125899906842624
}
// Int51 represents an signed 51 bit integer.
type Int51 int64

// Verify checks that value is in range of a 51 bit signed integer
func (value Int51) Verify() bool {
	return value < 1125899906842624 && value >= -1125899906842624
}

// Uint51 represents an unsigned 51 bit integer.
type Uint51 uint64

// Verify checks that value is in range of a 51 bit unsigned integer
func (value Uint51) Verify() bool {
	return value < 2251799813685248
}
// Int52 represents an signed 52 bit integer.
type Int52 int64

// Verify checks that value is in range of a 52 bit signed integer
func (value Int52) Verify() bool {
	return value < 2251799813685248 && value >= -2251799813685248
}

// Uint52 represents an unsigned 52 bit integer.
type Uint52 uint64

// Verify checks that value is in range of a 52 bit unsigned integer
func (value Uint52) Verify() bool {
	return value < 4503599627370496
}
// Int53 represents an signed 53 bit integer.
type Int53 int64

// Verify checks that value is in range of a 53 bit signed integer
func (value Int53) Verify() bool {
	return value < 4503599627370496 && value >= -4503599627370496
}

// Uint53 represents an unsigned 53 bit integer.
type Uint53 uint64

// Verify checks that value is in range of a 53 bit unsigned integer
func (value Uint53) Verify() bool {
	return value < 9007199254740992
}
// Int54 represents an signed 54 bit integer.
type Int54 int64

// Verify checks that value is in range of a 54 bit signed integer
func (value Int54) Verify() bool {
	return value < 9007199254740992 && value >= -9007199254740992
}

// Uint54 represents an unsigned 54 bit integer.
type Uint54 uint64

// Verify checks that value is in range of a 54 bit unsigned integer
func (value Uint54) Verify() bool {
	return value < 18014398509481984
}
// Int55 represents an signed 55 bit integer.
type Int55 int64

// Verify checks that value is in range of a 55 bit signed integer
func (value Int55) Verify() bool {
	return value < 18014398509481984 && value >= -18014398509481984
}

// Uint55 represents an unsigned 55 bit integer.
type Uint55 uint64

// Verify checks that value is in range of a 55 bit unsigned integer
func (value Uint55) Verify() bool {
	return value < 36028797018963968
}
// Int56 represents an signed 56 bit integer.
type Int56 int64

// Verify checks that value is in range of a 56 bit signed integer
func (value Int56) Verify() bool {
	return value < 36028797018963968 && value >= -36028797018963968
}

// Uint56 represents an unsigned 56 bit integer.
type Uint56 uint64

// Verify checks that value is in range of a 56 bit unsigned integer
func (value Uint56) Verify() bool {
	return value < 72057594037927936
}
// Int57 represents an signed 57 bit integer.
type Int57 int64

// Verify checks that value is in range of a 57 bit signed integer
func (value Int57) Verify() bool {
	return value < 72057594037927936 && value >= -72057594037927936
}

// Uint57 represents an unsigned 57 bit integer.
type Uint57 uint64

// Verify checks that value is in range of a 57 bit unsigned integer
func (value Uint57) Verify() bool {
	return value < 144115188075855872
}
// Int58 represents an signed 58 bit integer.
type Int58 int64

// Verify checks that value is in range of a 58 bit signed integer
func (value Int58) Verify() bool {
	return value < 144115188075855872 && value >= -144115188075855872
}

// Uint58 represents an unsigned 58 bit integer.
type Uint58 uint64

// Verify checks that value is in range of a 58 bit unsigned integer
func (value Uint58) Verify() bool {
	return value < 288230376151711744
}
// Int59 represents an signed 59 bit integer.
type Int59 int64

// Verify checks that value is in range of a 59 bit signed integer
func (value Int59) Verify() bool {
	return value < 288230376151711744 && value >= -288230376151711744
}

// Uint59 represents an unsigned 59 bit integer.
type Uint59 uint64

// Verify checks that value is in range of a 59 bit unsigned integer
func (value Uint59) Verify() bool {
	return value < 576460752303423488
}
// Int60 represents an signed 60 bit integer.
type Int60 int64

// Verify checks that value is in range of a 60 bit signed integer
func (value Int60) Verify() bool {
	return value < 576460752303423488 && value >= -576460752303423488
}

// Uint60 represents an unsigned 60 bit integer.
type Uint60 uint64

// Verify checks that value is in range of a 60 bit unsigned integer
func (value Uint60) Verify() bool {
	return value < 1152921504606846976
}
// Int61 represents an signed 61 bit integer.
type Int61 int64

// Verify checks that value is in range of a 61 bit signed integer
func (value Int61) Verify() bool {
	return value < 1152921504606846976 && value >= -1152921504606846976
}

// Uint61 represents an unsigned 61 bit integer.
type Uint61 uint64

// Verify checks that value is in range of a 61 bit unsigned integer
func (value Uint61) Verify() bool {
	return value < 2305843009213693952
}
// Int62 represents an signed 62 bit integer.
type Int62 int64

// Verify checks that value is in range of a 62 bit signed integer
func (value Int62) Verify() bool {
	return value < 2305843009213693952 && value >= -2305843009213693952
}

// Uint62 represents an unsigned 62 bit integer.
type Uint62 uint64

// Verify checks that value is in range of a 62 bit unsigned integer
func (value Uint62) Verify() bool {
	return value < 4611686018427387904
}
// Int63 represents an signed 63 bit integer.
type Int63 int64

// Verify checks that value is in range of a 63 bit signed integer
func (value Int63) Verify() bool {
	return value < 4611686018427387904 && value >= -4611686018427387904
}

// Uint63 represents an unsigned 63 bit integer.
type Uint63 uint64

// Verify checks that value is in range of a 63 bit unsigned integer
func (value Uint63) Verify() bool {
	return value < 9223372036854775808
}
